#Logging Configuration:
---
version: 1
disable_existing_loggers: False
formatters:
    simple:
      format: '[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s'
      datefmt: '%H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: Logs/info.log
        maxBytes: 30485760 # 30MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: Logs/errors.log
        maxBytes: 30485760 # 30MB
        backupCount: 20
        encoding: utf8

loggers:
    my_module:
        level: ERROR
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
...
